"use client";

import { useMemo, useState } from "react";

type Experience = {cat:string; date:string; role:string; company:string; bullets:string[]; noc?:boolean};

const comptiaVerifyUrl = "https://cp.certmetrics.com/CompTIA/en/public/verify/credential/e3efcae503dc48709ec0b12ccdbca464";

const experiences: Experience[] = [
  {cat:"Exploitation", noc:true, date:"Mai 2025 — Aujourd’hui", role:"Assistant d’exploitation IT & Support applicatif N1/N2", company:"BSIC TOGO S.A. · Lomé", bullets:["Support applicatif N1/N2 d’un écosystème bancaire centré sur Amplitude : Core Banking, Signature, reporting, Pro Extractor, 2c Designer et intégration des virements salaires.","Diagnostic des incidents de production liés aux traitements EOD/Cut-Off, aux bases Oracle 12c, aux serveurs Red Hat, aux contrôles SQL et aux anomalies transactionnelles.","Supervision des canaux digitaux et services clients : SMS/Mobile Banking, Internet Banking, plateforme digitale, e-Relevé et messagerie Exchange.","Surveillance de 18 GAB NCR/Wincor via ATM VIEW, qualification des alertes monétiques et des incidents LAN/VPN, avec une disponibilité supérieure à 95 % depuis mai 2025.","Support des interfaces critiques SWIFT, RTGS/BCEAO, KYC/Compliance, filtrage des transactions et services de transfert, avec escalade vers les équipes concernées.","Traçabilité des incidents dans GLPI et SOPRA, documentation des RCA, procédures de reprise, points de contrôle et indicateurs SLA/KPI pour renforcer la continuité de service."]},
  {cat:"Supervision", noc:true, date:"Mars 2025 — Mai 2025 · Mission clôturée", role:"Superviseur technique", company:"HOMINTEC TOGO · Lomé", bullets:["Pilotage de la continuité électrique sur trois sites nationaux de péage.","Suivi d’armoires électriques conformes à la norme CEI 61439-2.","Monitoring des systèmes automatisés TGMS Admin et FPGA, ainsi que de la vidéosurveillance.","Suivi des alarmes, coordination des interventions et rédaction des comptes rendus de continuité ; aucun incident opérationnel majeur signalé sur le périmètre suivi entre mars et mai 2025."]},
  {cat:"Réseaux", noc:true, date:"Depuis janvier 2025 · Missions saisonnières", role:"Consultant technique — Réseaux, systèmes & supervision", company:"SID Service Informatique et Design · Lomé", bullets:["Interventions ponctuelles, selon les besoins des missions, sur des infrastructures serveurs Windows et réseaux.","Diagnostic d’incidents réseau N1/N2 : routage, VLAN, switching, VoIP et connectivité.","Installation de solutions IoT de contrôle d’accès par badge et reconnaissance biométrique.","Contribution à l’administration Proxmox, au monitoring des ressources, aux RCA et au suivi des KPI."]},
  {cat:"Support IT", noc:true, date:"Avril 2020 — Décembre 2024", role:"Technicien Senior — Exploitation & Service Desk", company:"SICPA TOGO · Lomé", bullets:["Supervision de plus de 200 équipements industriels et analyse de logs Splunk, contribuant au maintien d’une disponibilité de 99,9 %.","95 % de respect des SLA sur plus de 100 tickets, de la qualification à la clôture dans ServiceNow.","Support utilisateurs N1/N2 multi-sites et déploiement des solutions de marquage numérique sur 10 sites industriels.","Plus de 100 interventions préventives et correctives sur imprimantes industrielles, capteurs et réseaux électriques, réduisant les temps d’arrêt de 20 %.","Suivi des procédures PRM/OPM de 25 équipements critiques et réduction de 30 % des incidents récurrents par les RCA et actions correctives.","Coordination de six techniciens sur le terrain et formation des collaborateurs, avec 95 % de satisfaction client."]},
  {cat:"Support IT", date:"Septembre 2019 — Avril 2020", role:"Technicien supérieur Télécom & Support applicatif", company:"AS PHARM TOGO · Lomé", bullets:["Déploiement et paramétrage des progiciels de gestion d’officine dans cinq établissements, améliorant l’efficacité opérationnelle de 30 %.","Support applicatif N1/N2 et maintenance du réseau pendant huit mois, du diagnostic à la résolution.","Formation de 12 collaborateurs, réduisant les erreurs de manipulation de 15 %.","Installation d’un réseau FAST sécurisé sur trois sites et maintien de 99 % de disponibilité pour le Dossier Pharmaceutique.","Élaboration de protocoles de sécurité ayant contribué à réduire de 15 % les incidents de sécurité."]},
  {cat:"Support IT", date:"Février 2019 — Juillet 2019", role:"Chef de projet IT — Parc & Helpdesk", company:"ESSN Groupe · Lomé / Cotonou", bullets:["Déploiement de solutions d’impression MFP sur sept sites, réduisant les coûts d’impression de 20 %.","Conception du câblage structuré de deux sites majeurs pour assurer une connectivité fiable.","Mise en place d’un archivage numérique pour plus de 500 documents.","Inventaire et documentation de 200 équipements, réduisant les pertes de 10 %.","Création d’une cellule Helpdesk ayant contribué à réduire de 35 % le temps de résolution des incidents."]},
  {cat:"Données", date:"Octobre 2018 — Mai 2019", role:"Opérateur de saisie", company:"CENI · Togo", bullets:["Modernisation d’une base électorale regroupant un million d’électeurs.","Supervision de la production et de la distribution de 500 000 cartes électorales.","Saisie avec un taux d’erreur inférieur à 1 % et organisation de l’archivage sécurisé.","Automatisation de procédures ayant contribué à réduire de 20 % les délais de traitement."]},
  {cat:"Stages", date:"Mai — Juillet 2018", role:"Stage — Génie mécanique & productique", company:"NSCT · Atakpamé", bullets:["Maintenance du condenseur, de l’égreneuse et des équipements de nettoyage de fibre.","Interventions sur le câblage des systèmes de contrôle, améliorant la fiabilité des installations de 10 %.","Rédaction de procédures techniques et assistance terrain dans le respect des règles HSE."]},
  {cat:"Support IT", date:"Février 2016 — Mai 2017", role:"Technico-commercial Réseau & Informatique", company:"TICNET · Lomé", bullets:["Maintenance de plus de 50 terminaux et 100 micro-ordinateurs, réduisant de 20 % les incidents techniques.","Gestion d’un portefeuille de 30 comptes clients et coordination des interventions techniques.","Création de supports numériques augmentant la visibilité des produits de 25 %."]},
  {cat:"Stages", date:"Juillet — Septembre 2016", role:"Stage — Maintenance IT & Réseaux", company:"BRAIN FACTORY SARL", bullets:["Maintenance informatique et réseau sur site avec un objectif de disponibilité de 99 %.","Installation et paramétrage de 10 routeurs.","Traitement d’incidents, documentation et propositions d’optimisation des installations."]},
  {cat:"Stages", date:"Août — Septembre 2015", role:"Stage — Solaire, réseaux & vidéosurveillance", company:"BAHAAU Technologies Consulting · Cotonou", bullets:["Installation de panneaux solaires, de systèmes de surveillance et de 30 caméras.","Tests de connexion et réglages réseau améliorant la stabilité et la performance de 20 %.","Actions correctives réduisant de 15 % les interruptions de service et montage de circuits domotiques."]},
];

const skills = {
  "NOC en production": {description:"Supervision et gestion d’incidents mobilisées dans des environnements réels.", items:["NOC","Network Operations Center","Monitoring","Alerting","Supervision réseau","Supervision des événements","Splunk","Centreon","ATM VIEW","Analyse de logs","Gestion des incidents","Diagnostic incident","Escalade","SLA","KPI","RCA","Disponibilité de service","Continuité de service","Documentation technique","Coordination prestataires"]},
  "Socle technique": {description:"Compétences systèmes, réseaux, exploitation et support qui soutiennent les opérations NOC.", items:["Support IT N1/N2","Service Desk","Helpdesk","ITSM","ServiceNow","GLPI","SOPRA","Windows 10/11","Windows Server","Linux","Active Directory","GPO","Microsoft 365","VMware","VirtualBox","Proxmox","TCP/IP","IPv4","LAN","DNS","DHCP","VPN","VLAN","Wi-Fi","Cisco","Mikrotik","Firewall","ACL","VoIP / SIP","SQL","MySQL","Power BI","Reporting","Maintenance préventive","Maintenance corrective"]},
  "Orientation SOC": {description:"Axe de formation clairement identifié, renforcé par CompTIA Security+, sans revendiquer une expérience SOC non acquise.", items:["CompTIA Security+","Sécurité réseau","Gestion des risques","Contrôle d’accès","IAM","Threats, Attacks & Vulnerabilities","Fondamentaux SOC","Cybersécurité","Détection des menaces","Vulnérabilités réseau","Concepts SIEM","Incident Response — fondamentaux","ITIL","Incident Management","Problem Management","Change Management","FTTH / FTTx / GPON — montée en compétence"]},
};

const metrics = [["99,9 %","de disponibilité sur 200+ équipements supervisés"],["−30 %","d’incidents récurrents après RCA et actions correctives"],["18","GAB suivis à >95 % depuis mai 2025"],["100+","tickets ServiceNow suivis avec 95 % de respect SLA"]];

export default function Home(){
  const [filter,setFilter]=useState("NOC / Supervision");
  const [skillFilter,setSkillFilter]=useState("Toutes");
  const cats=["NOC / Supervision","Tous",...Array.from(new Set(experiences.map(e=>e.cat)))];
  const shown=useMemo(()=>filter==="NOC / Supervision"?experiences.filter(e=>e.noc):filter==="Tous"?experiences:experiences.filter(e=>e.cat===filter),[filter]);
  const skillEntries=Object.entries(skills).filter(([k])=>skillFilter==="Toutes"||k===skillFilter);
  const navigation = [{label:"NOC / SOC",href:"#profil"},{label:"Expériences",href:"#experiences"},{label:"Compétences",href:"#competences"},{label:"Projets",href:"#projets"},{label:"Certifications",href:"#certifications"},{label:"Contact",href:"#contact"}];
  return <main>
    <header className="nav"><a className="brand" href="#accueil" aria-label="Accueil"><span>EPC</span><b>EPEY Pascal Chirac</b></a><nav>{navigation.map(x=><a key={x.href} href={x.href}>{x.label}</a>)}</nav><a className="navCta" href="/cv-epey-pascal-chirac.html" download>Télécharger le CV</a></header>
    <section id="accueil" className="hero">
      <div><p className="eyebrow">NOC · Supervision · Support IT N2 · CompTIA Security+</p><h1>Technicien NOC & Support IT N2<br/><em>Supervision, réseaux et sécurité opérationnelle.</em></h1><p className="lead">Plus de 5 ans d’expérience dans la surveillance d’environnements critiques, l’analyse de logs, le diagnostic d’incidents et la continuité de service. Mon expérience opérationnelle s’appuie sur Splunk, Centreon, ATM VIEW, ServiceNow, GLPI et SOPRA, avec une orientation SOC renforcée par CompTIA Security+.</p><div className="actions"><a className="primary" href="#experiences">Voir mon expérience NOC <span>↘</span></a><a className="secondary" href="/cv-epey-pascal-chirac.html" target="_blank">Consulter le CV ↗</a><a className="secondary" href="mailto:pascalchiracepey@gmail.com">Me contacter</a></div></div>
      <aside className="status"><div className="statusTop"><i></i> Préavis professionnel : moins de 30 jours</div><div className="heroVisual"><img src="/epey-pascal-chirac.jpeg" alt="Portrait professionnel d’EPEY Pascal Chirac"/><span>EPC</span></div><p>Lomé, Togo</p><p>Mobilité nationale & internationale</p><div className="miniTags"><span>NOC opérationnel</span><span>Security+ certifié</span><span>Français · Anglais B2</span></div></aside>
    </section>
    <section className="metrics" aria-label="Résultats clés">{metrics.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section>
    <section id="profil" className="section split"><div><p className="eyebrow">01 · Positionnement NOC / SOC</p><h2>Surveiller.<br/>Détecter.<br/>Rétablir.</h2></div><div className="profileText"><p className="profileLead">Technicien NOC & Support IT N2, issu d’une formation en électromécanique, engagé dans un Master en sécurité informatique et certifié CompTIA Security+.</p><p>Mon expérience NOC se traduit par la supervision d’équipements et de traitements critiques, l’analyse de logs et d’alertes, la qualification des incidents, l’escalade et la coordination des intervenants jusqu’au rétablissement du service.</p><p>Mon orientation SOC s’appuie désormais sur un socle vérifié en cybersécurité : sécurité réseau, contrôle d’accès, gestion des risques, détection des menaces et réponse aux incidents. Elle reste présentée comme une évolution structurée, sans revendiquer une expérience SOC que je n’ai pas encore exercée.</p><div className="positioningGrid"><article><span>NOC</span><b>Expérience opérationnelle</b><p>Monitoring, alerting, Splunk, Centreon, ATM VIEW, SLA/KPI, RCA et continuité de service.</p></article><article><span>SOC</span><b>Évolution structurée</b><p>CompTIA Security+, Master sécurité informatique, vulnérabilités réseau, détection des menaces et concepts SIEM.</p></article></div></div></section>
    <section id="experiences" className="section"><div className="sectionHead"><div><p className="eyebrow">02 · Expériences</p><h2>Un parcours au cœur<br/>des opérations.</h2></div><div className="filters" role="group" aria-label="Filtrer les expériences">{cats.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div></div><div className="timeline">{shown.map((e,i)=><article key={e.company}><div className="num">{String(i+1).padStart(2,"0")}</div><div className="date">{e.date}<span>{e.cat}</span></div><div><h3>{e.role}</h3><h4>{e.company}</h4><ul>{e.bullets.map(b=><li key={b}>{b}</li>)}</ul></div></article>)}</div></section>
    <section id="competences" className="section dark"><div className="sectionHead"><div><p className="eyebrow">03 · Compétences NOC / SOC</p><h2>NOC opérationnel.<br/>SOC mieux outillé.</h2><p className="skillIntro">Les compétences sont classées selon leur niveau réel : expérience NOC en production, socle technique opérationnel ou formation orientée SOC renforcée par CompTIA Security+.</p></div><select value={skillFilter} onChange={e=>setSkillFilter(e.target.value)} aria-label="Filtrer les compétences"><option>Toutes</option>{Object.keys(skills).map(k=><option key={k}>{k}</option>)}</select></div><div className="skillGrid">{skillEntries.map(([k,v])=><article key={k}><span>{k}</span><small>{v.description}</small><div>{v.items.map(x=><b key={x}>{x}</b>)}</div></article>)}</div></section>
    <section id="projets" className="section"><p className="eyebrow">04 · Projets clés</p><h2>Superviser, diagnostiquer<br/>et fiabiliser.</h2><div className="projects"><article><span>01</span><h3>Supervision & disponibilité industrielle</h3><p><strong>Compétences NOC mobilisées :</strong> monitoring de plus de 200 équipements, analyse de logs Splunk, RCA et actions correctives, avec une contribution à 99,9 % de disponibilité et à −30 % d’incidents récurrents.</p><b>SICPA TOGO</b></article><article><span>02</span><h3>Déploiement de SICPATRACE TOGO</h3><p><strong>Mon rôle :</strong> déploiement et paramétrage sur 10 sites industriels, puis maintenance des imprimantes, capteurs et connexions associées.</p><b>SICPA TOGO</b></article><article><span>03</span><h3>Fiabilisation du Service Desk</h3><p><strong>Mon rôle :</strong> qualification, diagnostic, communication, escalade et suivi jusqu’à clôture de plus de 100 tickets, avec 95 % de respect des SLA.</p><b>SICPA TOGO</b></article><article><span>04</span><h3>Continuité du parc GAB</h3><p><strong>Compétences NOC mobilisées :</strong> surveillance ATM VIEW, diagnostic, traçabilité et coordination prestataires, contribuant au maintien de 18 GAB à plus de 95 % de disponibilité.</p><b>BSIC TOGO</b></article><article><span>05</span><h3>Solution IoT de gestion de flotte</h3><p><strong>Mon rôle :</strong> intégration de capteurs Zigbee et GPS pour le suivi en temps réel des véhicules.</p><b>TICNET</b></article></div></section>
    <section id="certifications" className="section certs"><div><p className="eyebrow">05 · Formation</p><h2>Apprendre pour<br/>mieux sécuriser.</h2><div className="education"><p><b>Master en Sécurité informatique</b><span>LUCAS University College · 2024—2026</span></p><p><b>Licence en Génie électromécanique</b><span>UST-Togo · 2016—2018</span></p><p><b>DUT en Génie mécanique et productique</b><span>UST-Togo · 2014—2016</span></p><p><b>Baccalauréat scientifique</b><span>Lycée Moderne d’Adidogomé 1 · 2013</span></p></div></div><div className="certList"><p><span>01</span>CompTIA Security+ ce · SY0-701 · 22 août 2026 — 22 août 2029<br/><a href={comptiaVerifyUrl} target="_blank" rel="noreferrer">Vérification officielle CompTIA ↗</a></p>{["Cisco IT Essentials 7 · 2026","Cisco Introduction to Cybersecurity · 2026","Cisco — Appliquer l’IA : analyser les avis clients · 2026","PCI-DSS — Introduction · 2025","Risques opérationnels bancaires · 2025","Service Excellence for Agents — SICPA Group · 2021"].map((x,i)=><p key={x}><span>{String(i+2).padStart(2,"0")}</span>{x}</p>)}</div></section>
    <footer id="contact"><p className="eyebrow">06 · Contact</p><h2>Construisons un service<br/><em>qui ne s’arrête pas.</em></h2><p className="contactIntro">Vous recrutez pour une équipe support, exploitation ou supervision ? Échangeons sur vos enjeux de disponibilité, de support utilisateurs et de continuité de service.</p><div className="contactLinks"><a href="mailto:pascalchiracepey@gmail.com">pascalchiracepey@gmail.com ↗</a><a href="tel:+22891958980">+228 91 95 89 80 ↗</a><a href="https://linkedin.com/in/pascal-chirac-epey" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><div className="foot"><span>© 2026 EPEY Pascal Chirac · Dernière mise à jour : août 2026</span><a href="#accueil">Retour en haut ↑</a></div></footer>
  </main>
}
