"use client";

import { useMemo, useState } from "react";

const experiences = [
  {cat:"Exploitation", date:"Mai 2025 — Aujourd’hui", role:"Assistant d’exploitation IT & Support applicatif N1/N2", company:"BSIC TOGO S.A. · Lomé", bullets:["Maintien de plus de 98 % de disponibilité sur 18 GAB NCR/Wincor grâce à ATM VIEW, au diagnostic et à la coordination prestataires.","Support applicatif N1/N2 du Core Banking Amplitude, contrôle EOD/Cut Off et investigations SQL.","Traçabilité des incidents, SLA et escalades dans GLPI et SOPRA ; administration opérationnelle Active Directory."]},
  {cat:"Supervision", date:"Mars 2025 — Mai 2025", role:"Superviseur technique", company:"HOMINTEC Engineering Services · Lomé", bullets:["Contribution à la continuité opérationnelle de trois infrastructures nationales stratégiques.","Supervision de systèmes automatisés, alimentations sécurisées et vidéosurveillance ; suivi des alarmes et comptes rendus."]},
  {cat:"Réseaux", date:"Janvier 2025 — Février 2025", role:"Assistant technique — Réseaux & Supervision", company:"SID Service Informatique · Lomé", bullets:["Diagnostic d’incidents réseau N1/N2 : routage, VLAN, switching, VoIP et connectivité.","Administration Proxmox, monitoring des ressources, RCA et suivi KPI avec les équipes terrain et fournisseurs."]},
  {cat:"Support IT", date:"Avril 2020 — Décembre 2024", role:"Technicien Senior — Exploitation & Service Desk", company:"SICPA TOGO · Lomé", bullets:["95 % de respect des SLA sur plus de 100 tickets, de la qualification à la clôture dans ServiceNow.","Support utilisateurs N1/N2 multi-sites et déploiement des solutions de marquage numérique sur 10 sites industriels.","99,9 % de disponibilité sur plus de 200 équipements industriels grâce à la supervision, à l’analyse Splunk et à la maintenance proactive.","Plus de 100 interventions préventives et correctives sur imprimantes industrielles, capteurs et réseaux électriques, réduisant les temps d’arrêt de 20 %.","Suivi des procédures PRM/OPM de 25 équipements critiques et réduction de 30 % des incidents récurrents par les RCA et actions correctives.","Coordination de six techniciens sur le terrain et formation des collaborateurs, avec 95 % de satisfaction client."]},
  {cat:"Support IT", date:"Septembre 2019 — Avril 2020", role:"Technicien supérieur Télécom & Support applicatif", company:"AS PHARM TOGO · Lomé", bullets:["Déploiement et paramétrage des progiciels de gestion d’officine dans cinq établissements, améliorant l’efficacité opérationnelle de 30 %.","Support applicatif N1/N2 et maintenance du réseau pendant huit mois, du diagnostic à la résolution.","Formation de 12 collaborateurs, réduisant les erreurs de manipulation de 15 %.","Installation d’un réseau FAST sécurisé sur trois sites et maintien de 99 % de disponibilité pour le Dossier Pharmaceutique.","Élaboration de protocoles de sécurité ayant contribué à réduire de 15 % les incidents de sécurité."]},
  {cat:"Support IT", date:"Février 2019 — Juillet 2019", role:"Chef de projet IT — Parc & Helpdesk", company:"ESSN Groupe · Lomé / Cotonou", bullets:["Déploiement de solutions d’impression MFP sur sept sites, réduisant les coûts d’impression de 20 %.","Conception du câblage structuré de deux sites majeurs pour assurer une connectivité fiable.","Mise en place d’un archivage numérique pour plus de 500 documents.","Inventaire et documentation de 200 équipements, réduisant les pertes de 10 %.","Création d’une cellule Helpdesk ayant contribué à réduire de 35 % le temps de résolution des incidents."]},
  {cat:"Données", date:"Octobre 2018 — Mai 2019", role:"Opérateur de saisie", company:"CENI · Togo", bullets:["Modernisation d’une base électorale regroupant un million d’électeurs.","Supervision de la production et de la distribution de 500 000 cartes électorales.","Saisie avec un taux d’erreur inférieur à 1 % et organisation de l’archivage sécurisé.","Automatisation de procédures ayant contribué à réduire de 20 % les délais de traitement."]},
  {cat:"Stages", date:"Mai — Juillet 2018", role:"Stage — Génie mécanique & productique", company:"NSCT · Atakpamé", bullets:["Maintenance du condenseur, de l’égreneuse et des équipements de nettoyage de fibre.","Interventions sur le câblage des systèmes de contrôle, améliorant la fiabilité des installations de 10 %.","Rédaction de procédures techniques et assistance terrain dans le respect des règles HSE."]},
  {cat:"Support IT", date:"Février 2016 — Mai 2017", role:"Technico-commercial Réseau & Informatique", company:"TICNET · Lomé", bullets:["Maintenance de plus de 50 terminaux et 100 micro-ordinateurs, réduisant de 20 % les incidents techniques.","Gestion d’un portefeuille de 30 comptes clients et coordination des interventions techniques.","Création de supports numériques augmentant la visibilité des produits de 25 %."]},
  {cat:"Stages", date:"Juillet — Septembre 2016", role:"Stage — Maintenance IT & Réseaux", company:"BRAIN FACTORY SARL", bullets:["Maintenance informatique et réseau sur site avec un objectif de disponibilité de 99 %.","Installation et paramétrage de 10 routeurs.","Traitement d’incidents, documentation et propositions d’optimisation des installations."]},
  {cat:"Stages", date:"Août — Septembre 2015", role:"Stage — Solaire, réseaux & vidéosurveillance", company:"BAHAAU Technologies Consulting · Cotonou", bullets:["Installation de panneaux solaires, de systèmes de surveillance et de 30 caméras.","Tests de connexion et réglages réseau améliorant la stabilité et la performance de 20 %.","Actions correctives réduisant de 15 % les interruptions de service et montage de circuits domotiques."]},
];

const skills = {
  "Support & ITSM":["Support IT N1/N2","Service Desk","Helpdesk","ITSM","ServiceNow","GLPI","SOPRA","SLA","ITIL","Diagnostic incident","Résolution d’incidents","Support utilisateurs","Support client technique","Escalade","Coordination prestataires"],
  "Systèmes":["Windows 10/11","Windows Server","Linux","Active Directory","GPO","Microsoft 365","VMware","VirtualBox","Proxmox","Sauvegarde / restauration"],
  "Réseaux":["TCP/IP","LAN","DNS","DHCP","VPN","VLAN","Wi-Fi","Cisco","Mikrotik","Firewall","ACL","VoIP / SIP"],
  "Supervision & données":["Centreon","Splunk","Power BI","ATM VIEW","SQL","MySQL","Reporting","KPI","Analyse de logs","Documentation technique"],
  "Exploitation":["Disponibilité de service","Continuité de service","Maintenance préventive","Maintenance corrective","Incident Management","Problem Management","Change Management","RCA"],
};

const metrics = [["100+","tickets traités"],["95 %","de respect SLA"],["200+","équipements supervisés"],["99,9 %","de disponibilité"],["−30 %","d’incidents récurrents"],["18","GAB à >98 %"]];

export default function Home(){
  const [filter,setFilter]=useState("Tous");
  const [skillFilter,setSkillFilter]=useState("Toutes");
  const cats=["Tous",...Array.from(new Set(experiences.map(e=>e.cat)))];
  const shown=useMemo(()=>filter==="Tous"?experiences:experiences.filter(e=>e.cat===filter),[filter]);
  const skillEntries=Object.entries(skills).filter(([k])=>skillFilter==="Toutes"||k===skillFilter);
  return <main>
    <header className="nav"><a className="brand" href="#accueil" aria-label="Accueil"><span>EPC</span><b>EPEY Pascal Chirac</b></a><nav>{["Profil","Expériences","Compétences","Projets","Certifications","Contact"].map(x=><a key={x} href={`#${x.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}`}>{x}</a>)}</nav><a className="navCta" href="/cv-epey-pascal-chirac.html" download>Télécharger le CV</a></header>
    <section id="accueil" className="hero">
      <div><p className="eyebrow">Support · Exploitation · Réseaux</p><h1>Technicien Support IT N2<br/><em>orienté continuité de service.</em></h1><p className="lead">Plus de 5 ans d’expérience en support utilisateurs, ITSM, supervision et diagnostic d’incidents dans des environnements bancaires, industriels et multi-sites à forte criticité.</p><div className="actions"><a className="primary" href="#experiences">Découvrir mon parcours <span>↘</span></a><a className="secondary" href="mailto:pascalchiracepey@gmail.com">Me contacter</a></div></div>
      <aside className="status"><div className="statusTop"><i></i> Disponible sous moins d’un mois</div><div className="heroVisual"><img src="https://d8j0ntlcm91z4.cloudfront.net/user_3HgmnBWTu1vSZE1SreObuYxKRG3/hf_20260809_183544_fb52b125-9f1e-4275-9966-756319bae0a8.png" alt="Composition abstraite représentant réseaux, supervision et continuité de service"/><span>EPC</span></div><p>Lomé, Togo</p><p>Mobilité nationale & internationale</p><div className="miniTags"><span>Permis A, B</span><span>Français · Anglais B2</span></div></aside>
    </section>
    <section className="metrics" aria-label="Résultats clés">{metrics.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section>
    <section id="profil" className="section split"><div><p className="eyebrow">01 · Profil</p><h2>Faire fonctionner l’IT.<br/>Et le faire durer.</h2></div><div className="profileText"><p>J’assure la prise en charge des incidents de bout en bout : qualification, diagnostic, résolution, documentation et escalade. Mon approche associe support utilisateur, exploitation et compréhension réseau pour rétablir le service vite et durablement.</p><p>Habitué aux environnements critiques, je suis les SLA et KPI, analyse les logs et coordonne équipes techniques et prestataires. FTTH, FTTx et GPON constituent un axe de montée en compétence appuyé sur ce socle réseau — sans revendiquer d’expérience fibre terrain.</p></div></section>
    <section id="experiences" className="section"><div className="sectionHead"><div><p className="eyebrow">02 · Expériences</p><h2>Un parcours au cœur<br/>des opérations.</h2></div><div className="filters" role="group" aria-label="Filtrer les expériences">{cats.map(c=><button className={filter===c?"active":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div></div><div className="timeline">{shown.map((e,i)=><article key={e.company}><div className="num">{String(i+1).padStart(2,"0")}</div><div className="date">{e.date}<span>{e.cat}</span></div><div><h3>{e.role}</h3><h4>{e.company}</h4><ul>{e.bullets.map(b=><li key={b}>{b}</li>)}</ul></div></article>)}</div></section>
    <section id="competences" className="section dark"><div className="sectionHead"><div><p className="eyebrow">03 · Compétences</p><h2>La boîte à outils<br/>d’un service fiable.</h2></div><select value={skillFilter} onChange={e=>setSkillFilter(e.target.value)} aria-label="Filtrer les compétences"><option>Toutes</option>{Object.keys(skills).map(k=><option key={k}>{k}</option>)}</select></div><div className="skillGrid">{skillEntries.map(([k,v])=><article key={k}><span>{k}</span><div>{v.map(x=><b key={x}>{x}</b>)}</div></article>)}</div></section>
    <section id="projets" className="section"><p className="eyebrow">04 · Projets clés</p><h2>Des résultats mesurables.</h2><div className="projects"><article><span>01</span><h3>Fiabilisation du Service Desk</h3><p>Atteinte de 95 % de respect SLA sur 100+ tickets via ServiceNow, avec qualification, traitement, escalade et suivi jusqu’à clôture.</p><b>SICPA TOGO</b></article><article><span>02</span><h3>Disponibilité industrielle</h3><p>Contribution à 99,9 % de disponibilité sur 200+ équipements par supervision, maintenance proactive et analyse de logs Splunk.</p><b>SICPA TOGO</b></article><article><span>03</span><h3>Continuité du parc GAB</h3><p>Maintien de 18 GAB à plus de 98 % de disponibilité grâce à ATM VIEW, au diagnostic et à la coordination prestataires.</p><b>BSIC TOGO</b></article></div></section>
    <section id="certifications" className="section certs"><div><p className="eyebrow">05 · Formation</p><h2>Apprendre pour<br/>mieux sécuriser.</h2><div className="education"><p><b>Master en Sécurité informatique</b><span>LUCAS University College · 2024—2026</span></p><p><b>Licence en Génie électromécanique</b><span>UST-Togo · 2016—2018</span></p><p><b>DUT en Génie mécanique et productique</b><span>UST-Togo · 2014—2016</span></p><p><b>Baccalauréat scientifique</b><span>Lycée Moderne d’Adidogomé 1 · 2013</span></p></div></div><div className="certList">{["Cisco IT Essentials 7 · 2026","Cisco Introduction to Cybersecurity · 2026","Cisco — Appliquer l’IA : analyser les avis clients · 2026","PCI-DSS — Introduction · 2025","Risques opérationnels bancaires · 2025","Service Excellence for Agents — SICPA Group · 2021"].map((x,i)=><p key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</p>)}</div></section>
    <footer id="contact"><p className="eyebrow">06 · Contact</p><h2>Construisons un service<br/><em>qui ne s’arrête pas.</em></h2><div className="contactLinks"><a href="mailto:pascalchiracepey@gmail.com">pascalchiracepey@gmail.com ↗</a><a href="tel:+22891958980">+228 91 95 89 80 ↗</a><a href="https://linkedin.com/in/pascal-chirac-epey" target="_blank" rel="noreferrer">LinkedIn ↗</a></div><div className="foot"><span>© 2026 EPEY Pascal Chirac</span><a href="#accueil">Retour en haut ↑</a></div></footer>
  </main>
}
